# Generated by Django 3.1.7 on 2021-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('password', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=40)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='members',
        ),
    ]
