# Generated by Django 3.1.7 on 2021-02-25 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='music',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newapp.member'),
        ),
    ]
