# Generated by Django 3.1.7 on 2021-02-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_auto_20210225_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='fname',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='section',
            name='music',
            field=models.CharField(max_length=30),
        ),
    ]
