# Generated by Django 3.1.7 on 2021-02-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_auto_20210225_1446'),
    ]

    operations = [
        migrations.DeleteModel(
            name='section',
        ),
    ]
